### ISSUE TITLE
Кэшировать курсы валют

### ISSUE THREAD

**Issue by marinsky** [exelban/money_bot#1]
Отличный и полезный бот!
По поводу сервиса с курсами валют - маленькое предложение. У всех бесплатных сервисов, что я знаю, курсы обновляются не в режиме реального времени (что и не особо нужно в данном случае), а один раз в 30, 60, 120, ... минут. И у всех у них есть какие-либо ограничения: на количество запросов, на скорость ответа.  [Используемый сервис](http://www.currencyconverterapi.com/pricing) также обновляет курсы раз в 30 минут. Собственно предложение простое - бот может запрашивать курс раз в 30 минут и сохранять результат. А затем использовать сохраненный курс для конвертации валют из сообщений чата. Это значительно ускорит время ответа бота.

**Comment by exelban** [comment]
Спасибо, как только будет свободное времья допишу кеширование. И есть вопрос, какую бд лучше использовать сдесь или просто json?

**Comment by marinsky** [comment]
БД сложновато-то будет для такой задачи. Лучше просто в памяти хранить. Да, можно json сохранять, можно массив чисел (quotes).

**Comment by exelban** [comment]
Ok, спасибо.
